spring.application.name=session12_demo2

#  cấu ình thyleaf
#tiền tố
spring.thymeleaf.prefix=classpath:/templates/
#hậu tố
spring.thymeleaf.suffix=.html
#có lưu trữ tạm thời hay không
spring.thymeleaf.cache=false

server.port=2505    